# Fix numeric keypad in nano
alias nano='nano -K'

alias upgrade='apt-get update && apt-get upgrade'
alias bowerinstall='sudo bower install --allow-root'
alias bowerlist='sudo bower list --allow-root'


alias provision='cd {{ home }}/ansible-playbook-server && ./provision.sh $1'
alias deploy='{{ scripts_path }}/deploy.sh $1'

{% if is_dev -%}
alias provisionall='cd {{ home }}/ansible-playbook-server && ./provision_dev.sh'
alias provisioninit='cd {{ home }}/ansible-playbook-server && ./provision.sh init_dev'
alias develop='{{ scripts_path }}/develop.sh $1'
alias tox='{{ scripts_path }}/tox.sh $1'
alias makemessages='{{ scripts_path }}/makemessages.sh $1'
alias save='{{ scripts_path }}/fastcommit.sh $1'
{%- endif %}

{% if is_prod -%}
alias provisionall='cd {{ home }}/ansible-playbook-server && ./bootstrap && ./provision_prod.sh'
alias provisioninit='cd {{ home }}/ansible-playbook-server && ./bootstrap && ./provision.sh init_prod'
alias deploysite='{{ scripts_path }}/deploy_desecho.org.sh'
alias restart='{{ scripts_path }}/restart.sh $1'
alias debug='{{ scripts_path }}/debug.sh $1'
{%- endif %}
