# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "olbat/tiny-core-micro"
    config.disksize.size = '120GB'
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.customize ["modifyvm", :id, "--vram", "64"]
        vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
        vb.customize ['modifyvm', :id, '--accelerate3d', 'off']
        vb.memory = 8192
        vb.cpus = 4
    end
    config.vm.hostname = 'ubuntu'
end
